# Generated by Django 4.0.5 on 2022-06-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpart',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='car',
            field=models.ManyToManyField(to='core.carpart'),
        ),
    ]
